package main

const hookHeader = "Generated by prepare-commit-msg-ai"

const (
	app     = "prepare-commit-msg-ai"
	banner  = "Prepare Git Commit Message with AI"
	author  = "@dwisiswant0"
	version = "v0.0.1"

	usage = `Usage:
  %s [COMMAND]`
	commands = `Commands:
  install           Install hook in current Git project (alias: isntall, i)
  uninstall         Uninstall generated hook file (alias: unisntall, u)
  edit              Edit hook file (alias: ed, e)`
	examples = `Examples:
  %s install`
)
